services:
  - type: web
    name: agrismart-backend
    env: node
    rootDir: AgriSmart-Backend
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
    buildCommand: npm install
    startCommand: npm start
